### ISSUE TITLE
Saint Lucia HA reported timestamp / timezone bug

### ISSUE THREAD

**Issue by mundanelunacy** [Path-Check/safeplaces-frontend#1]
https://github.com/tripleblindmarket/safe-places/issues/65

**Comment by mundanelunacy** [comment]
@kylemtowle 

![image](https://user-images.githubusercontent.com/3040401/79987512-7ba65980-84e8-11ea-98d4-359bc3943032.png)

Could you try out the code on dev_mvp_timezone to see if this issue is sufficiently resolved for MVP2?

Implemented [moment.tz.guess()](https://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/) to identify user's timezone and format accordingly.  

Not sure if solves the issue on Jim's computer but apparently using this instead of the toLocale() call is supposed to be more consistent across browsers.

**Comment by kylemtowle** [comment]
Verified it looks good on my end, but I couldn't re-produce. Asked Saint Lucia to re-validate with new code.

**Comment by mundanelunacy** [comment]
@kylemtowle 

Any feedback from Jim?  If you don't mind, I'd like to close this issue for now.  I'll merge the dev_mvp_timezone code

**Comment by kylemtowle** [comment]
Customer Jim Johnson verified it as fixed on his end.
