### ISSUE TITLE
Provide better UX for bad or malformed case data imports

### ISSUE THREAD

**Issue by aiyan** [Path-Check/safeplaces-frontend#102]
In the open file dialog, we can filter out unacceptable file types (i.e. only show files with a `.json` extension).

Moreover, the web app will break if the imported data is not in the proper format. We should validate the imported file, catch any errors, and inform the user that the data is invalid.

![image](https://user-images.githubusercontent.com/48393820/82154960-6c909e00-983f-11ea-8b43-72ef50fbf327.png)

**Comment by iamdcj** [comment]
File import is longer available in the current version of the application.
