### ISSUE TITLE
Improve filter-by-date performance by delaying map updates

### ISSUE THREAD

**Issue by aiyan** [Path-Check/safeplaces-frontend#103]
## Problem
When dragging the date range slider, the map attempts to re-render every time the knob's position changes. This significantly impacts performance and lags the entire interface.

## Possible Solution
Do not update the map until the user lets go of the knob. However, the list of points on the sidebar can be updated to give live visual feedback.

**Comment by iamdcj** [comment]
Fixed by https://github.com/Path-Check/safeplaces-frontend/pull/226
