### ISSUE TITLE
Is the Content-Type for XMLHttpRequests supposed to be application/x-www-form-urlencoded?

### ISSUE THREAD

**Issue by elHoudini9** [Path-Check/safeplaces-frontend#12]
I'm not sure about marking this as a bug yet.

As I tried to connect the frontend to my backend, I encountered a problem.
I set the `has_backend` var to `true` and tried the `'/login'` endpoint. 

My backend is receiving this body:
```json
{ "{ username: 'hi', password: 'hi' }'": "" }
```
(Which is not the payload found in the [spec](https://github.com/Path-Check/safeplaces-frontend/blob/master/Safe-Places-Server.md#login))

I looked around the client code and it seems like the Request’s Content-Type Header is set to `"application/x-www-form-urlencoded"` instead of `"application/json"`

Setting it to `"application/json"` sends the payload as expected:
```json
{ "username": "hi", "password": "hi" }
```

Is this intentional? If so, I could have the server code work around this, but I believe that most front-end http libraries are expecting the latter for sending payloads.

This is hardcoded to be `"application/x-www-form-urlencoded"` in both of the index.html files, inside of the `doXHR` function.

Curious about viability of changing this now to use the Content-Type: application/json header.

```js
function doXHR(method, url, param, auth, creds) {
  ...
    // Make the request
    if (method === "POST" && isDefined(param)) {
      var data = param;
      if (isDefined(creds)) {
        req.setRequestHeader("Authorization", creds);
      }
      req.setRequestHeader(
        "Content-type",
        "application/x-www-form-urlencoded"
      );
      req.send(data);
    } else {
      req.setRequestHeader("Authorization", "Basic " + auth);
      req.send();
    }
  });
}
```

**Comment by mundanelunacy** [comment]
@elHoudini9 

https://github.com/Path-Check/safeplaces-frontend/blob/dev_mvp/Safe-Places-Server.md

For `dev_mvp` I propose we change `Content-type` to `application/json` for both requests and responses
