### ISSUE TITLE
The algorithm for identifying travel is too sensitive

### ISSUE THREAD

**Issue by AdamLeonSmith** [Path-Check/safeplaces-frontend#23]
I was gardening on a 3m by 3m balcony for an hour and quite a few of the data points are showing as travel, with speeds between 0.1 and 0.3 mph.  Can we set a floor for the speed that the algorithm considers as travel?

Note this is on the MASTER branch.

**Comment by mundanelunacy** [comment]
@AdamLeonSmith Is this still occurring on dev_mvp ?
