### ISSUE TITLE
FEATURE REQ:  Travel speed is shown as mph, would be better to show as kph in most countries

### ISSUE THREAD

**Issue by AdamLeonSmith** [Path-Check/safeplaces-frontend#24]

**Comment by mundanelunacy** [comment]
<img width="252" alt="Screen Shot 2020-04-29 at 11 42 08 PM" src="https://user-images.githubusercontent.com/3040401/80609511-1ff14880-8a73-11ea-9fdd-f4a797254e8d.png">

What branch are you using?  on `dev_mvp` I'm see travel speed in kph

**Comment by AdamLeonSmith** [comment]
Retested and agree, closing.
