### ISSUE TITLE
User case for multiple Contact Tracer inputs

### ISSUE THREAD

**Issue by mundanelunacy** [Path-Check/safeplaces-frontend#30]
@kylemtowle @penrods 

Here is my understanding of the use cases for has_backend false and true cases

**has_backend = false**

1. Contact Tracer (CT) receives file from the patient 
2. CT opens Location Scrubber tool
3. CT clicks "Load" and selects file from dialogue
4. CT redacts data 
5. CT clicks "Save" and enters filename in dialogue
6. CT sends file to Health Authority Admin (HAA)
7. HAA opens Publisher tool
8. HAA clicks "Load" and selects file from dialogue
9. HAA reviews data
10. HAA clicks "Publish" and enters filename in dialogue

**has_backend = true  AS-IS** 

1. Contact Tracer (CT) receives file from the patient 
2. CT opens Location Scrubber tool
3. CT clicks "Load" and selects file from dialogue
4. CT redacts data 
5. CT clicks "Save" and data is transmitted to BE
6. HAA opens Publisher tool
7. HAA clicks "Load" which loads redacted data 
8. HAA reviews data
10. HAA clicks "Publish" 

Question:  What happens at step 6 if there are a dozen contract tracers who all saved data in the BE at the same time?  Does s/he open all redacted data?  Latest data? 

My understanding is that the HAA is an authority figure who reviews the CTs work by approving/disapproving of the publishing of data.  Current UI seems to support this use-case in  **has_backend = false** mode since a single CT passes the HAA a single file.  Unclear how the UI is supposed to support this in **has_backend = true** mode. 

Here is how I propose we modify the UI for dev_mvp.  Please let me know if this sound right to you

**has_backend = true  TO-BE** 

1. Contact Tracer (CT) receives file from the patient 
2. CT opens Location Scrubber tool
3. CT clicks "Load" and selects file from dialogue
4. CT redacts data 
5. CT clicks "Save" and data is transmitted to BE
6. _Location scrubber tool spits out an ID number onto the screen_
7. _CT shares this ID number to HAA_
8. HAA opens Publisher tool
9. _HAA enters ID number clicks "Load" which loads redacted data associated with ID_
10. HAA reviews data
11. HAA clicks "Publish"

**Comment by penrods** [comment]
The HAA gets all of the contact traces.  In this tool they don't know/need to know what individual it came from.  Right now the only additional "redaction" they can do is time.

At the time I wrote this it wasn't completely clear if 14 days was the right timeframe to look back, although that seems to have settled since then.  That capability should probably be hard-coded.  Also, i could see I could see adding the ability for the HAA to delete points in this tool -- e.g. determining that a specific area is too sensitive for public release for some reason outside of the contact tracer guidelines.

I do not believe there is any justification for the HAA reviewing individual records in this tool.  They are looking at the all the points as a whole set.

**Comment by mundanelunacy** [comment]
@penrods 

Thanks for your reply.  For context - this is for current MVP and so new features such as "deletion of points" is out of scope.  Would like to tackle this with a "minimum" solution (as the name implies)

> I do not believe there is any justification for the HAA reviewing individual records in this tool. They are looking at the all the points as a whole set.

What about human error ? 

At the moment, the publisher tool would pull down redacted points from all CTs who saved using location scrubber.  For example would HAA reject the whole set, if there was only one erroneous file out of a hundred?

**Comment by penrods** [comment]
How would they recognize that a contact tracer made a mistake?  I also don't think losing a single file at a time makes an error any more obvious.  I can't imagine opening more than a couple files one at a time - that doesn't seem practical.

I definitely understand wanting to re-redact a file, and the Save operation implies that a saved record would overwrite another previously saved on the same name - although the API definition isn't explicit about this and probably should be clarified.

**Comment by mundanelunacy** [comment]
I think I understand now.  

For purposes of MVP I think underlying data probably looks like this :

<img width="1126" alt="Screen Shot 2020-04-29 at 12 44 20 AM" src="https://user-images.githubusercontent.com/3040401/80508319-dd683700-89b2-11ea-9e08-60c65d8c8f05.png">
