### ISSUE TITLE
[dev_mvp]  IE11: Is not loading google map

### ISSUE THREAD

**Issue by AfshinShahabi** [Path-Check/safeplaces-frontend#43]
Open IE11
Browse to: https://safeplaces.extremesolution.com/location-scrubber/index.html
Expected Result:
Loads the SafePath WEB app

Actual Results:
Displays a blank page.

![image](https://user-images.githubusercontent.com/64602888/80735287-5192ff80-8ac5-11ea-8c9e-14c3c921f191.png)

**Comment by mundanelunacy** [comment]
@AfshinShahabi 

- Does the login page work?
- Does https://maps.google.com work on the same environment?

**Comment by mundanelunacy** [comment]
@AfshinShahabi 
Scrap my previous comment.  Took a look at console errors on ie11.  Looks like errors are due to usage of modern Javascript notation that Microsoft is no longer supporting.  Will see if I can get this to work using a transpiler (Babel)

**Comment by mundanelunacy** [comment]
`dev_mvp` working on ie11
<img width="1680" alt="Screen Shot 2020-05-04 at 4 38 21 PM" src="https://user-images.githubusercontent.com/3040401/80945154-25a9ae00-8e26-11ea-9892-211e3b9552bb.png">
