### ISSUE TITLE
[dev_mvp] cannot publish data due to date issues

### ISSUE THREAD

**Issue by AdamLeonSmith** [Path-Check/safeplaces-frontend#46]
![image](https://user-images.githubusercontent.com/48051844/80832455-9b263c00-8be4-11ea-8ba4-2561494736ea.png)

I successfully redacted data, saved it, loaded in the publishing tool.  When I try and publish, I get an invalid date issue.

It looks like a strange datetime_created value is being sent to the back end:

`{"datetime_created":"Fri, 27 Mar 2020 04:32:12 GMT","organization_id":"a88309c2-26cd-4d2b-8923-af0779e423a3","safe_path":{"authority_name":"Fake Organization","concern_points":[{"latitude":12.34,"longitude":12.34,"time":123},{"latitude":12.34,"longitude":12.34,"time":456}],"info_website":"https://www.something.gov/path/to/info/website","publish_date_utc":1584924583},"user_id":"a88309c1-26cd-4d2b-8923-af0779e423a3"}`

It looks a lot like hardcoded date above!

**Comment by mundanelunacy** [comment]
this one is caused by this issue on the backend
https://github.com/Path-Check/safeplaces-backend/issues/32

**Comment by mundanelunacy** [comment]
@krishnadurai
Looks like `datetime_created` being returned is static as well.  JYFI, I use `publish_date` in the UI so not a high priority fix

**Comment by krishnadurai** [comment]
@mundanelunacy Path-Check/safeplaces-backend#34 will solve both of these issues.

**Comment by zmon** [comment]
@mundanelunacy The [API documentation](https://github.com/Path-Check/safeplaces-frontend/blob/master/Safe-Places-Server.md) uses the variable name `publish_date_utc`.  Should the documentation be changed?

**Comment by altoplano** [comment]
I've argued the "_utc" has some value to clarify that the times should not be server location dependent without need to reference the SPI spec.
One or the other end of this should change though (i.e. code or spec.).

**Comment by mundanelunacy** [comment]
@zmon
The spec was modified on `dev_mvp`.  and one of the changes was `publish_date_utc` →  `publish_date` 
https://github.com/Path-Check/safeplaces-frontend/blob/dev_mvp/Safe-Places-Server.md

@altoplano 
Correct.  Previous spec had `_utc` in the parameter name, but was passing a Unix timestamp integer.  _Somewhat_ confusing, so we aligned to timestamp

**Comment by mundanelunacy** [comment]
@krishnadurai Thanks ! 
@AdamLeonSmith fix confirmed on staging
<img width="1992" alt="Screen Shot 2020-05-04 at 2 40 28 PM" src="https://user-images.githubusercontent.com/3040401/80938796-664cfb80-8e15-11ea-9ca9-7d3a3490778c.png">

**Comment by altoplano** [comment]
I'll agree that saying it is a unix timestamp does imply it is UTC but you have to go read the spec to know that. I might naively expect *publish_date* to be something like *May 3, 2020* and not a timestamp at all (not that adding "_utc" changes it much ;-) )
Perhaps more consequencial: doesn't the name change in the dev_mvp spec means any points of interest published to the old spec will no longer be readable?
