### ISSUE TITLE
[dev_mvp] unable to upload file for redaction

### ISSUE THREAD

**Issue by AdamLeonSmith** [Path-Check/safeplaces-frontend#49]
When I upload a file for redaction it fails, and there is an error in the console.
![image](https://user-images.githubusercontent.com/48051844/80948526-2f152500-8dea-11ea-8f97-c982de351dd3.png)

**Comment by mundanelunacy** [comment]
@AdamLeonSmith saw that as well and fixed.  Could you retry?

**Comment by AdamLeonSmith** [comment]
confirmed fixed
