### ISSUE TITLE
The publishing tool fails to combine files

### ISSUE THREAD

**Issue by mundanelunacy** [Path-Check/safeplaces-frontend#5]
https://github.com/tripleblindmarket/safe-places/issues/59

**Comment by mundanelunacy** [comment]
Unfortunately I cannot provide the test data I am using as it is personal data.

Steps to reproduce
Redact two files containing different data (in this case, one from Spain, one from the US) from the same day
In the publishing tool, load both files
Publish the data

Expected behaviour
The file exported from the publishing process should contain both redacted datasets

Actual behaviour
Only one dataset is included. The following is visible in the console:

Uncaught TypeError: Cannot read property 'length' of undefined
at updateStats (index.html:1504)
at updateExposurePoints (index.html:1404)
at updateDateRange (index.html:1343)
at HTMLDocument. (index.html:1314)
at e (jquery.min.js:2)
at t (jquery.min.js:2)

**Comment by mundanelunacy** [comment]
@kylemtowle 
@penrods 

**What your take on the above?** 

Should we support the ability to load multiple files in the publishing tool on the MVP?  
I'd prefer holding off implementation on this until the next version.  For now, suggest simply showing an error message if the user tries to load more than one file.

**Comment by mundanelunacy** [comment]
per conversation with @kylemtowle will not support loading of multiple files at this time, however will gracefully handle errors

**Comment by AdamLeonSmith** [comment]
That's fine, but note the product spec says that files are to be aggregated, and it would a significant privacy issue if each individuals location history was to be stored unaggregated.

**Comment by kylemtowle** [comment]
Adam,
You are correct, but that happens by default when the app is used with a fully implemented backend, which is the intended production use.
Thanks,Kyle
    On Saturday, April 25, 2020, 05:51:35 AM PDT, Adam Leon Smith <notifications@github.com> wrote:  
 
 


That's fine, but note the product spec says that files are to be aggregated, and it would a significant privacy issue if each individuals location history was to be stored unaggregated.

**Comment by mundanelunacy** [comment]
@AdamLeonSmith 

Could you test again on dev_mvp?  

When I loaded these two files on the publisher tool, all points showed up without any problems. 


[files.zip](https://github.com/Path-Check/safeplaces-frontend/files/4557829/files.zip)

**Comment by mundanelunacy** [comment]
@AdamLeonSmith sorry.  Accidentally got issue #26 and #5 confused with that commit.  This issue is still open
