### ISSUE TITLE
[dev-mvp] Notice on READMEs for safeplaces repository for project's current status.

### ISSUE THREAD

**Issue by krishnadurai** [Path-Check/safeplaces-frontend#53]
We need to add notices to safe-places frontend and backend repository, indicating:

1. The project is still under development
1. The release date (time frame) for the first deployable version of the project.
1. That there can be breaking changes within the code base.

cc @mundanelunacy @kylemtowle @sherifkozman

**Comment by mundanelunacy** [comment]
@krishnadurai 

That's a good point.  Suggest two things:

1.  Look for a project that communicates their roadmap on Git really well (and copy copy copy !)
2. Switch to semantic versioning in our naming convention, i.e. dev_mvp = 0.10.x, dev_react = 1.0.x

> That there can be breaking changes within the code base.
@krishnadurai Semantic versioning should make this clear to 90% of devs, right?

**Comment by krishnadurai** [comment]
>     2. Switch to semantic versioning in our naming convention, i.e. dev_mvp = 0.10.x, dev_react = 1.0.x

I agree about semantic versioning and the codes used here.

I'll do some research and raise this PR.

**Comment by krishnadurai** [comment]
@mundanelunacy Here's a sample PR in the back-end. If you think its fine, I'll raise similar one for FE.

Path-Check/safeplaces-backend#39

**Comment by mundanelunacy** [comment]
@krishnadurai added project status to README.  Should probably converge on semantic versioning at a later date
