### ISSUE TITLE
[dev-mvp]: "{{baseUrl}}/users" API call returns '504 Gateway Time-out'

### ISSUE THREAD

**Issue by AfshinShahabi** [Path-Check/safeplaces-frontend#54]
1. Run the API: https://api.express.safeplaces.extremesolution.com/users

Expected Results:
returns null or list of users 

Actual Results:
Returns:
<html>

<head>
	<title>504 Gateway Time-out</title>
</head>

<body>
	<center>
		<h1>504 Gateway Time-out</h1>
	</center>
	<hr>
	<center>nginx/1.17.8</center>
</body>

**Comment by krishnadurai** [comment]
@AfshinShahabi @AdamLeonSmith is this a part of our API spec?

cc @mundanelunacy

**Comment by AdamLeonSmith** [comment]
Discussed with @krishnadurai - this doesn't exist in the MVP spec.  It was referenced in some of the API specs Peter was working on - is this post MVP?
