### ISSUE TITLE
[dev-mvp]: Running the "{{baseUrl}}/" generates 504

### ISSUE THREAD

**Issue by AfshinShahabi** [Path-Check/safeplaces-frontend#55]
Steps to repro:

1. Run the https://api.express.safeplaces.extremesolution.com by postman 

Expected results:
Returns null or data 

Actual Results:
Returns time out 504:
<html>

<head>
	<title>504 Gateway Time-out</title>
</head>

<body>
	<center>
		<h1>504 Gateway Time-out</h1>
	</center>
	<hr>
	<center>nginx/1.17.8</center>
</body>

</html>

**Comment by krishnadurai** [comment]
@AfshinShahabi @AdamLeonSmith is this a part of our API spec?

cc @mundanelunacy

**Comment by AdamLeonSmith** [comment]
Discussed with @krishnadurai - this doesn't exist in the MVP spec.  It was referenced in some of the API specs Peter was working on - is this post MVP?
