### ISSUE TITLE
[dev-mvp]: Running the "{{baseUrl}}/validate" API generates 504

### ISSUE THREAD

**Issue by AfshinShahabi** [Path-Check/safeplaces-frontend#57]
Steps to repro:

Run the https://api.express.safeplaces.extremesolution.com/validate  by postman
Expected results:
Returns null or data

Actual Results:
Returns time out 504:

<title>504 Gateway Time-out</title>
504 Gateway Time-out

**Comment by AdamLeonSmith** [comment]
Discussed with @krishnadurai - this doesn't exist in the MVP spec.  It was referenced in some of the API specs Peter was working on - is this post MVP?
