### ISSUE TITLE
A JS error popup appears when a redacted file is loaded into the publishing tool 

### ISSUE THREAD

**Issue by mundanelunacy** [Path-Check/safeplaces-frontend#6]
https://github.com/tripleblindmarket/safe-places/issues/58

**Comment by huskywhale** [comment]
Taking up this issue

**Comment by huskywhale** [comment]
Update: I don't get the message now, is it possible for you to upload the file which fices error

**Comment by mundanelunacy** [comment]
> **Steps to reproduce:**
> 
> 1. Redact a file and export from the redaction tool
> 2. Load the file into the publishing tool
> 
> **Expected Behaviour**
> File is loaded with no errors
> 
> **Actual Behaviour**
> The file is loaded, but a popup appears that says "[object file]". The below stack trace is visible in the console:
> 
> jquery.min.js:2 Uncaught TypeError: Cannot read property 'length' of undefined
> at updateStats (index.html:1504)
> at updateExposurePoints (index.html:1404)
> at updateDateRange (index.html:1343)
> at HTMLDocument. (index.html:1314)
> at e (jquery.min.js:2)
> at t (jquery.min.js:2)

**Comment by huskywhale** [comment]
@mundanelunacy  looks like the old issue is closed, lets close this as well

**Comment by mundanelunacy** [comment]
@huskywhale got it.  Thanks for looking into it
