### ISSUE TITLE
[dev_react] Loading a file results in an error

### ISSUE THREAD

**Issue by mundanelunacy** [Path-Check/safeplaces-frontend#60]
<img width="1270" alt="Screen Shot 2020-05-05 at 10 11 22 PM" src="https://user-images.githubusercontent.com/3040401/81069886-77812f80-8f1d-11ea-881e-13b6912d5a68.png">

- Successful with `/examples/robert-safe-paths.json`
- Failed with the `/Sample_PrivateKit.json` in root dir

@huskywhale Could you please look into this ?

**Comment by huskywhale** [comment]
I can take this one!

**Comment by mundanelunacy** [comment]
Thanks !

**Comment by mundanelunacy** [comment]
@AdamLeonSmith Would it be possible for devs to have additional examples of the JSON files exported from PrivateKit?  We've been working exclusively with the one at the root of the git repo and would be helpful to have some more
