### ISSUE TITLE
Implement API Authentication

### ISSUE THREAD

**Issue by mundanelunacy** [Path-Check/safeplaces-frontend#63]
Design requirements:
* Tokens should persist in redux store 
* Need to implement logout button
* Design flexibly to allow HA to switch out Auth schemes including:
  * Bearer Auth (Priority)
  * OAUTH2
  * LDAP

**Comment by mundanelunacy** [comment]
@Utzel-Butzel @elHoudini9 Haven't looked too deeply into the code.  Do we have this implemented to a certain degree ?

**Comment by iamdcj** [comment]
@FacundoMalgieri @aiyan I suspect the work you've being doing around this could impact the status of this ticket?

**Comment by aiyan** [comment]
@iamdcj I think we can close this
