### ISSUE TITLE
Add Entry fails with empty Redux store

### ISSUE THREAD

**Issue by mundanelunacy** [Path-Check/safeplaces-frontend#64]
<img width="1074" alt="Screen Shot 2020-05-06 at 9 50 44 PM" src="https://user-images.githubusercontent.com/3040401/81181104-e8d8e500-8fe6-11ea-866a-e90f4918c251.png">

Get the above error when trying to "Add entry" to the map

Steps to reproduce:
- Open app
- Open _Inspect -> Application_ tab
- Right-Click _Storage -> Local storage_
- Select "Clear"
- Click "Add Entry" button in UI
- Enter GPS Coordinates
- Click "Add to Tracks" button

**Comment by sanjeevkkansal** [comment]
We are working on this

**Comment by sanjeevkkansal** [comment]
it has be fixed by https://github.com/Path-Check/safeplaces-frontend/commit/b24b76ae0f092fc2c6ad78204e9ea85e1c127f63
