### ISSUE TITLE
Open multiple bubbles on the map when multiple entries are selected

### ISSUE THREAD

**Issue by mundanelunacy** [Path-Check/safeplaces-frontend#65]
<img width="1678" alt="Screen Shot 2020-05-06 at 10 22 04 PM" src="https://user-images.githubusercontent.com/3040401/81182039-4457a280-8fe8-11ea-9571-b76c06427358.png">

Presently only one bubble appears on the map when multiple entries are selected

**Comment by iamdcj** [comment]
@mundanelunacy I think this feature/multi-select in general should be discussed with design - it would be nice for this to be captured in JIRA for the upcoming sprints.

**Comment by iamdcj** [comment]
Multi-select from sidebar not in scope.
