### ISSUE TITLE
Add hover-over tooltips on buttons in "Add Entry dialog"

### ISSUE THREAD

**Issue by mundanelunacy** [Path-Check/safeplaces-frontend#67]
<img width="432" alt="Screen Shot 2020-05-06 at 10 27 57 PM" src="https://user-images.githubusercontent.com/3040401/81182563-ea0b1180-8fe8-11ea-9603-50002d060aec.png">

**Comment by aiyan** [comment]
I can take this one!

**Comment by aiyan** [comment]
I have finished this task. I will create a PR soon, but currently, the latest commit in `dev_react` does not run on my computer - issue #71.

Below is a preview:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/48393820/81513232-d9aeab80-92f4-11ea-813f-5391fde36bdb.gif)
