### ISSUE TITLE
[dev_mvp] Cookie issue

### ISSUE THREAD

**Issue by AdamLeonSmith** [Path-Check/safeplaces-frontend#68]
When using publisher, I see the following warning in the console:

`A cookie associated with a cross-site resource at https://google.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`

**Comment by aiyan** [comment]
This is nothing we have to worry about. It is not related to our code; in fact, Google has to fix their cookie settings on _their servers._

This is essentially Chrome's way of spreading the word about their deprecation of the `SameSite` default setting as `Lax`. For those curious, you can check out Chrome's rollout [here](https://www.chromium.org/updates/same-site). They've temporarily postponed enforcement in light of COVID-19.
