### ISSUE TITLE
[dev_react] Map not updating on File import

### ISSUE THREAD

**Issue by mundanelunacy** [Path-Check/safeplaces-frontend#74]
Steps to reproduce

1. Open App
2. Click "Import" button
3. Load `Sample_PrivateKit.json`

<img width="1680" alt="Screen Shot 2020-05-11 at 6 44 49 PM" src="https://user-images.githubusercontent.com/3040401/81547990-8f423300-93b7-11ea-847b-1d64be6d888b.png">

4. Adjust date slider

<img width="1682" alt="Screen Shot 2020-05-11 at 6 45 06 PM" src="https://user-images.githubusercontent.com/3040401/81548007-9406e700-93b7-11ea-9760-153cdb21912c.png">

**Comment by sanjeevkkansal** [comment]
Working on it.

**Comment by iamdcj** [comment]
File import is longer available in the current version of the application.
