### ISSUE TITLE
Credentials for the Location Viewers / Scrubber and Publisher section in the master branch

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [Path-Check/safeplaces-frontend#92]
Hi friend,

I would like to know what are the credentials for the **_Location Viewers / Scrubber_** and **_Publisher_** section in the master branch

Both sections ask for the

- [x] username
- [x] password

I will appreciate your answer,

BTW..  excellent work!

**Comment by AdamLeonSmith** [comment]
Hi, in the hosted test environment, it is admin/admin.  I'm not entirely sure what the resolution for this issue should be as it is not related to the "reference implementation" tracked in GitHub.  Perhaps adding it to the developer onboarding docs?

**Comment by ChrisMichaelPerezSantiago** [comment]
Right @AdamLeonSmith ,

I find it ideal to be added to the developer onboarding docs
